[package]
name = "warp-sessions"
license = "MIT"
version = "1.0.14"
authors = ["ajp <8890201+ajpauwels@users.noreply.github.com>"]
edition = "2018"
description = "Generic session middleware for the warp HTTP framework"
repository = "https://github.com/ajpauwels/warp-sessions.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-session = "2.0.1"
async-trait = "0.1.42"
serde = { version = "1.0.123", features = ["derive"] }
warp = "0.3.0"
tokio = { version = "1.2.0", features = ["macros", "rt-multi-thread"] }
http = "0.2.3"
