[package]
name = "warp-sessions"
license = "MIT"
version = "1.0.0"
authors = ["ajp <8890201+ajpauwels@users.noreply.github.com>"]
edition = "2018"
description = "Generic session middleware for the warp HTTP framework"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-session = "2.0.1"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.22"
warp = "0.2"
tokio = { version = "0.2", features = ["macros"] }
